services:
  ros2-workshop-turtlebot3:
    container_name: ros2-workshop-turtlebot3
    build:
      context: ..
      dockerfile: docker/Dockerfile.amd
      args:
        - AMENT_WORKSPACE_DIR=${AMENT_WORKSPACE_DIR}
        - USERNAME=${USERNAME:-developer}
        - UID=${UID}
        - GID=${GID}
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - YOUR_IP=${YOUR_IP}
      - ROBOT_IP=${ROBOT_IP}
      - TURTLEBOT3_MODEL=burger
      - GZ_IP=${YOUR_IP}
      - AMD_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    extra_hosts:
      - "${ROBOT_HOSTNAME}:${ROBOT_IP}"
    # Required for communicating over the network
    network_mode: "host"
    runtime: amd
    privileged: true
    tty: true
    volumes:
      # Required for accessing hardware
      #- /dev:/dev
      # Required for accessing storage media
      #- /media:/media
      - ../src:${AMENT_WORKSPACE_DIR}/src
      # Required for ROS 2 shared memory communication
      #- /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

