services:
  ros2-workshop-turtlebot3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - AMENT_WORKSPACE_DIR=${AMENT_WORKSPACE_DIR}
        - USERNAME=${USERNAME:-developer}
        - UID=${UID}
        - GID=${GID}
    container_name: ros2-workshop-turtlebot3
    env_file:
      - turtlebot.env
    extra_hosts:
      - "${ROBOT_HOSTNAME}:${ROBOT_IP}"
    # Required for communicating over the network
    network_mode: "host"
    # Required for accessing hardware
    #privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ../src:${AMENT_WORKSPACE_DIR}/src
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
      - ../config/default.rviz:/root/.rviz2/default.rviz
      - ../maps:/turtlebot_ws/maps
